name: CI

on:
  push:
    branches:
    - main
    - release/**
    paths:
    - src/**
    - samples/**
    - .github/workflows/ci.yml
  pull_request:
    branches:
    - main
    - release/**
    paths:
    - src/**
    - samples/**
    - .github/workflows/ci.yml

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'src/Legerity.sln'
      BUILD_VERSION: '1.0.0'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" >> $GITHUB_ENV
      shell: pwsh

    - name: Validate Build Version
      run: |
          echo "${{env.BUILD_VERSION}}"

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore

    - name: Publish
      if: startsWith(github.ref, 'refs/heads/release')
      run: nuget push *.nupkg -s 'https://api.nuget.org/v3/index.json' -k ${{secrets.NUGET_API_KEY}}
